/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrijavaRouteImport } from './routes/prijava'
import { Route as RegistracijaRouteImport } from './routes/registracija'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijavaRoute = PrijavaRouteImport.update({
  id: '/prijava',
  path: '/prijava',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistracijaRoute = RegistracijaRouteImport.update({
  id: '/registracija',
  path: '/registracija',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prijava': typeof PrijavaRoute
  '/registracija': typeof RegistracijaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prijava': typeof PrijavaRoute
  '/registracija': typeof RegistracijaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prijava': typeof PrijavaRoute
  '/registracija': typeof RegistracijaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prijava' | '/registracija'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prijava' | '/registracija'
  id: '__root__' | '/' | '/prijava' | '/registracija'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrijavaRoute: typeof PrijavaRoute
  RegistracijaRoute: typeof RegistracijaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijava': {
      id: '/prijava'
      path: '/prijava'
      fullPath: '/prijava'
      preLoaderRoute: typeof PrijavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registracija': {
      id: '/registracija'
      path: '/registracija'
      fullPath: '/registracija'
      preLoaderRoute: typeof RegistracijaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrijavaRoute: PrijavaRoute,
  RegistracijaRoute: RegistracijaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
