/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IstorijaRouteImport } from './routes/istorija'
import { Route as PrijavaRouteImport } from './routes/prijava'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RegistracijaRouteImport } from './routes/registracija'
import { Route as TreningRouteImport } from './routes/trening'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IstorijaRoute = IstorijaRouteImport.update({
  id: '/istorija',
  path: '/istorija',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijavaRoute = PrijavaRouteImport.update({
  id: '/prijava',
  path: '/prijava',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistracijaRoute = RegistracijaRouteImport.update({
  id: '/registracija',
  path: '/registracija',
  getParentRoute: () => rootRouteImport,
} as any)
const TreningRoute = TreningRouteImport.update({
  id: '/trening',
  path: '/trening',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/istorija': typeof IstorijaRoute
  '/prijava': typeof PrijavaRoute
  '/profil': typeof ProfilRoute
  '/registracija': typeof RegistracijaRoute
  '/trening': typeof TreningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/istorija': typeof IstorijaRoute
  '/prijava': typeof PrijavaRoute
  '/profil': typeof ProfilRoute
  '/registracija': typeof RegistracijaRoute
  '/trening': typeof TreningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/istorija': typeof IstorijaRoute
  '/prijava': typeof PrijavaRoute
  '/profil': typeof ProfilRoute
  '/registracija': typeof RegistracijaRoute
  '/trening': typeof TreningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/istorija'
    | '/prijava'
    | '/profil'
    | '/registracija'
    | '/trening'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/istorija'
    | '/prijava'
    | '/profil'
    | '/registracija'
    | '/trening'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/istorija'
    | '/prijava'
    | '/profil'
    | '/registracija'
    | '/trening'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  IstorijaRoute: typeof IstorijaRoute
  PrijavaRoute: typeof PrijavaRoute
  ProfilRoute: typeof ProfilRoute
  RegistracijaRoute: typeof RegistracijaRoute
  TreningRoute: typeof TreningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/istorija': {
      id: '/istorija'
      path: '/istorija'
      fullPath: '/istorija'
      preLoaderRoute: typeof IstorijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijava': {
      id: '/prijava'
      path: '/prijava'
      fullPath: '/prijava'
      preLoaderRoute: typeof PrijavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registracija': {
      id: '/registracija'
      path: '/registracija'
      fullPath: '/registracija'
      preLoaderRoute: typeof RegistracijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trening': {
      id: '/trening'
      path: '/trening'
      fullPath: '/trening'
      preLoaderRoute: typeof TreningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  IstorijaRoute: IstorijaRoute,
  PrijavaRoute: PrijavaRoute,
  ProfilRoute: ProfilRoute,
  RegistracijaRoute: RegistracijaRoute,
  TreningRoute: TreningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
